build:
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
                    -
                        command: 'vendor/bin/phpunit --coverage-clover=build/logs/clover.xml'
                        coverage:
                            file: 'build/logs/clover.xml'
                            format: 'clover'
            environment:
                node:
                    version: 6.0.0
        tests: true
checks:
    php: true
filter:
    excluded_paths: [tests/*]
coding_style:
    php: {  }